Feature users djoser
Mobile-app-promotions-and-discounts/backend pull request #25
Opened 2023-11-22 18:07 UTC by BnamoRS

Пока закоментил в users admin.py list_edittable, чтобы проходили миграции.

Установил djoser и simple-jwt.

Добавил endpoints для users в api и настройки установленных библиотек в settings.py

В модели Users изменил поле username на EmailField и сделал его уникальным.

2023-11-22 18:23 UTC, sukhovarina approved these changes

2023-11-23 15:52 UTC, rakikz approved these changes

2023-11-23 15:52 UTC, rakikz commented on products/migrations/0001_initial.py
нужны ли нам миграции в девелопе?

2023-11-23 15:52 UTC, rakikz commented on users/models.py
> +        verbose_name="email",
юзернейм как имейл? не нужна ли отдельная графа?

2023-11-23 17:59 UTC, valerycode requested changes
Есть небольшие замечания

2023-11-23 17:59 UTC, valerycode commented on cherry/settings.py
> +    "DEFAULT_AUTHENTICATION_CLASSES": (
Забыл прописать DEFAULT_PERMISSION_CLASSES?

2023-11-23 17:59 UTC, valerycode commented on cherry/settings.py
> +    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
Почему такой большой срок жизни токена? Пока можно сделать 1 день, но стоит поднять этот вопрос на встрече.

2023-11-23 18:10 UTC, sic15 approved these changes

2023-11-23 18:23 UTC, valerycode commented on requirements.txt
>  asgiref==3.7.2
Давай уберем этот файл из текущего PR, так как он у тебя уже есть в PR#28

2023-11-23 18:27 UTC, BnamoRS commented on cherry/settings.py
> +    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
Срок жизни токена большой на время разработки. Чтобы не терять время при ручном тестировании на создание токена ежедневно

2023-11-23 18:34 UTC, BnamoRS commented on users/models.py
> +        verbose_name="email",
Отдельное поле тоже есть. Просто не прописано явно, но наследуется от AbstractUser. Сделал так на первом этапе, потому что разговор был про авторизацию по email. Эти два поля очень жестко завязаны с менеджером модели. Мне кажется это вопрос для обсуждения.

2023-11-23 18:41 UTC, BnamoRS commented on users/admin.py
> +    # list_editable = (
Закомментированный код оставил, потому что мне так удобнее работать. Когда сомневаюсь в чем то оставляю несколько вариантов. Потом выбираю нужный, лишнее удаляю.

2023-11-23 18:45 UTC, BnamoRS commented on cherry/settings.py
> +    "DEFAULT_AUTHENTICATION_CLASSES": (
На данном этапе разработки не стал прописывать, потому что еще не обсуждали ограничения.

По умолчанию 'DEFAULT_PERMISSION_CLASSES': [
   'rest_framework.permissions.AllowAny',
]

2023-11-23 20:33 UTC, BnamoRS commented on requirements.txt
>  asgiref==3.7.2
в данном файле добавил установленные библиотеки:
djangorestframework-simplejwt==5.3.0
djoser==2.2.2

Без них API Users нет

2023-11-23 20:54 UTC, valerycode commented on cherry/settings.py
> +    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
Принято)

2023-11-23 20:55 UTC, valerycode approved these changes
Ок

2023-11-23 20:55 UTC, merged