документация API + фильтрация
Mobile-app-promotions-and-discounts/backend pull request #38
Opened 2023-11-25 14:31 UTC by sic15

1) документация API доступна по адресу /swagger/
2) настроена развернутая выдача get запроса по адресам /stores/, stores-with-product/, сategories/

2023-11-26 13:45 UTC, rakikz approved these changes

2023-11-26 13:45 UTC, rakikz commented on users/models.py
> +    email = models.EmailField(
пропустил согласование этого изменения. оно ничего не ломает?

2023-11-26 19:25 UTC, valerycode requested changes
Есть замечания

2023-11-26 19:25 UTC, valerycode commented on products/models.py
> +        'Изображение магазина',
Почему появилось это поле?

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +    """Вспомогательный сериализатор для получения товаров по категориям."""
Не нужен, будет использоваться ProductSerializer

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +class StoreLongSerializer(serializers.ModelSerializer):
Давай назовем StoreRroductsSerializer, так сразу понятно о чем речь:)

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +    discount = DiscountSerializer()
Давай переименуем так -  ProductInStoreSerializer, будет понятнее)

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +    """Вспомогательный сериализатор для получения информации о скидке."""
Давай уберем слово вспомогательный(здесь и везде)

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +    """Вспомогательный сериализатор для получения адреса магазина."""
Давай уберем слово вспомогательный

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +class CategoryShortSerializer(serializers.ModelSerializer):
Давай вернем старое название сериализатору

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +    """Вспомогательный сериализатор для получения краткой информации о категории."""
Давай уберем слово "вспомогательный"

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> +class StoreShortSerializer(serializers.ModelSerializer):
Давай вернем прежнее название сериалайзера

2023-11-26 19:25 UTC, valerycode commented on api/serializers.py
> -    """Сериализатор для получения всех магазинов для конкретного товара."""
Зачем нам этот сериализатор, если он нигде не используется(ни в одной вьюхе)? Давай удалим

2023-11-26 19:32 UTC, sic15 commented on requirements.txt
> +drf-yasg
этот кусок взять из лекции яндекс практикума. У этой штуки нет версии

2023-11-26 19:34 UTC, sic15 commented on api/serializers.py
> +    """Вспомогательный сериализатор для получения адреса магазина."""
наоборот так понятнее какие главные, а какие нужны в промежуточных моделях

2023-11-26 19:38 UTC, sic15 commented on api/serializers.py
> +class CategoryShortSerializer(serializers.ModelSerializer):
я не против переименовать, то старый не гоидтся. Один дает более полную информацию, другой которкую. Просто CategorySerializer будет непонятно. Если идеи как сделать лучше кроме короткий и длинный, то давай поправим

2023-11-26 19:38 UTC, sic15 commented on api/serializers.py
> +    """Вспомогательный сериализатор для получения краткой информации о категории."""
уже выше написала

2023-11-26 19:40 UTC, sic15 commented on api/serializers.py
> -    """Сериализатор для получения всех магазинов для конкретного товара."""
он используется в ProductSerializer

2023-11-27 18:57 UTC, valerycode requested changes
См.замечания

2023-11-29 19:03 UTC, sukhovarina approved these changes

2023-11-30 20:40 UTC, BnamoRS approved these changes

2023-11-30 20:40 UTC, BnamoRS commented on users/models.py
>      username = models.EmailField(
Здесь уже точно будет конфликт. Когда будем сливать придется его разрешать.

2023-12-04 10:31 UTC, valerycode approved these changes
LGTM

2023-12-04 18:56 UTC, merged