Feature cd dockerfile
Mobile-app-promotions-and-discounts/backend pull request #47
Opened 2023-11-27 21:08 UTC by BnamoRS

1. Добавил в зависимости  gunicorn и psycopg2-binary
2. Написал Dockerfile
3. Изменил в settings.py ALLOWED_HOSTS. Теперь в .env можно перечислять разрешенные хосты через запятую
4. Поправил настройки статики.
5. Создал папку infra. Положил туда настройки nginx и docker-compose.yaml.

P.S. Файлы в infra немного отличаются от тех, что на сервере. На сервере вынес папку на директорию выше backend и поменял пути до .env и Dockerfile. Логика в файлах осталась та же.

2023-11-28 03:08 UTC, rakikz approved these changes

2023-11-28 16:42 UTC, valerycode requested changes
Молодец! Отличная работа! Есть небольшие замечания

2023-11-28 16:42 UTC, valerycode commented on infra/docker-compose.yaml
> +      - 80:80
Забыл кавычки - "80:80"

2023-11-28 16:42 UTC, valerycode commented on infra/docker-compose.yaml
> +version: '3.8'
Предлагаю немного поправить текущую структуру: файл docker-compose.yml принято выносить на уровень проекта(туда же, где у тебя сейчас Dockerfile), а директорию с настройками Nginx принято называть nginx(у тебя называется infra). Со сменой структуры надо будет немного поправить docker-compose.

2023-11-28 19:28 UTC, BnamoRS commented on infra/docker-compose.yaml
> +version: '3.8'
Название infra и структуру брал из курса Практикума. Коммерческого опыта нет, поэтому информацию как принято, брать неоткуда. Поправлю.

По факту на сервере файлы nginx.conf и docker-compose.yaml будут находиться в директории пользователя и там же будет папка backend. Пути в файлах естественно исправлены, о чем написал в P.S. Так же в курсе упоминалось, что данные файлы копируются на сервер вручную и меняются крайне редко. Положил в папку backend для ревью.

Деплой проекта будет происходить не через DockerHub, так как общего аккаунта для образа у нас там нет. Первоначально клон репозитория. А последующее обновление через git pull репозитория на сервере, удаление контейнера и образа и создание их заново из обновленного кода.

Структуру и пути поправлю, но на сервере это не будет иметь большого значения. 

К сожалению, изначально неверно создал структуру проекта. Не хватает директории выше backend, в которой хранились бы файлы git  и настройки инфраструктуры. Как исправить на данном этапе не знаю.

2023-11-28 19:29 UTC, BnamoRS commented on cherry/settings.py
> +        'ENGINE': os.environ.get('DB_ENGINE'),
Не совсем понимаю тогда назначение файла .env.example. Если он присутствует в репозитории и в нем есть все секретные данные, чем это отличается от из наличия в коде на этапе разработки? Если там только пример секретных переменных, то каким образом остальные члены команды получат данные для запуска контейнеров docker-compose.

2023-11-28 19:51 UTC, valerycode commented on cherry/settings.py
> +        'ENGINE': os.environ.get('DB_ENGINE'),
В файле .env.example **НЕ** выкладываем сами секреты. Этот файл нужен в качестве **примера заполнения** файла .env. Все секретные данные передаются между разработчиками через защищенные каналы связи(в нашем случае в чате телеграма).

2023-11-29 19:03 UTC, sukhovarina approved these changes

2023-11-30 00:37 UTC, sic15 approved these changes
оставила один комментарий. Посмотри пожалуйста

2023-11-30 00:37 UTC, sic15 commented on cherry/settings.py
>  DEBUG = True
DEBUG = os.getenv('DEBUG', default='True') == 'True'
вот такую штуку тут нужно сделать. Вроде ревьювер рб этом тоже писал

2023-11-30 04:51 UTC, rakikz commented on cherry/settings.py
>  DEBUG = True
Наверное по умолчанию всё-таки false надо ставить, нет?

2023-11-30 04:57 UTC, sic15 commented on cherry/settings.py
>  DEBUG = True
Нет. Тут ведь сравнение. Если в env лежит False, то будет сравнение False == True. И в итоге это False как и нужно

2023-11-30 16:48 UTC, valerycode requested changes
Мелкие правки

2023-11-30 16:48 UTC, valerycode commented on cherry/settings.py
>  DEBUG = True
@rakikz верно подметил, молодец!) @sic15 Про то, как это работает можно вот тут почитать - https://rusingh.com/all-been-there-boolean-environment-variables/
@BnamoRS можешь, пожалуйста, вместо `DEBUG=True` записать вот так `DEBUG = os.environ.get('DEBUG', False) == 'True'`, а в переменные окружения добавить `DEBUG=True`. Пока идет разработка можно работать с включенным дебагером, позднее достаточно будет убрать эту переменную из окружения, чтобы отключить его работу.

2023-11-30 16:48 UTC, valerycode commented on cherry/settings.py
> +        'ENGINE': os.environ.get('DB_ENGINE'),
@BnamoRS Заменить DB_NAME на POSTGRES_DB

2023-11-30 17:52 UTC, BnamoRS commented on cherry/settings.py
>  DEBUG = True
А еще по моему тогда и вот так можно сделать:

DEBUG = bool(os.environ.get('DEBUG', False))

Тогда любое значение DEBUG в .env даст True, кроме пустой строки. А по умолчанию будет  False

2023-11-30 18:07 UTC, valerycode commented on cherry/settings.py
>  DEBUG = True
@BnamoRS Абсолютно верно!) Можно оформить и так, как ты говоришь.

2023-11-30 18:09 UTC, valerycode approved these changes
LGTM

2023-11-30 18:11 UTC, merged