Fix products images
Mobile-app-promotions-and-discounts/backend pull request #57
Opened 2023-12-04 16:43 UTC by BnamoRS

Ветка не от последней develop. Думаю будут конфликты.

Модель изображений это просто связь продукта с изображением. В модели продукта по факту поле main_image это основное изображение и связь images - это дополнительные изображения продукта.

- переделал модель продукта в  плане изображений
- изменил модель для доп. изображений
- добавил сериалайзер для изображений
- немного поменял сериалайзер продуктов для выдачи изображений
- добавил модель изображений продукта в админку.

ПОСЛЕ РЕВЬЮ ИСПРАВИЛ.

- слил эту ветку с текущей develop и разрешил конфликты.
- немного изменил выдачу по favorites, добавил поле рейтинг.
- исправил замечания.

2023-12-04 22:13 UTC, sic15 approved these changes

2023-12-05 16:00 UTC, rakikz approved these changes

2023-12-05 16:00 UTC, rakikz commented on api/views.py
>      serializer_class = ProductSerializer
вот это тогда не надо. а то опять запутаемся

2023-12-05 16:00 UTC, rakikz commented on api/serializers.py
> +        return product
а вот этот метод разве нельзя вынести в родной сериализатор?

2023-12-06 16:41 UTC, BnamoRS commented on api/views.py
> +        return get_object_or_404(Product, id=self.kwargs.get('product_id'))
Здесь flake8 ругнулся. И мне кстати наоборот говорили на ревью, незачем создавать переменную. Работает и так и так. Как правильнее я не уверен.

2023-12-06 16:49 UTC, BnamoRS commented on api/serializers.py
> +        return product
Набор полей разный.
Мне кажется так будет нагляднее. Хотя можно подумать.
Возможно он понадобится для добавления товара в магазин. Пока не додумал этот вариант.

Это вообще начальный вариант куда думать. Я хотел чтобы в ветке просто посмотрели.

2023-12-06 16:52 UTC, BnamoRS commented on api/views.py
>      serializer_class = ProductSerializer
Согласен. Забыл удалить. Это вообще здесь уже не нужно.

2023-12-07 16:24 UTC, rakikz commented on api/views.py
> +        return get_object_or_404(Product, id=self.kwargs.get('product_id'))
вроде как без переменной правильнее. память экономит

2023-12-07 21:12 UTC, sic15 approved these changes

2023-12-09 11:19 UTC, sic15 approved these changes

2023-12-12 19:43 UTC, TSergey1 approved these changes

2023-12-12 20:10 UTC, valerycode requested changes
См. замечания

2023-12-13 17:32 UTC, BnamoRS commented on products/models.py
> +        max_length=13,
Да

2023-12-14 07:38 UTC, valerycode approved these changes
LGTM

2023-12-14 07:38 UTC, merged