flake8_isort
Mobile-app-promotions-and-discounts/backend pull request #80
Opened 2023-12-28 19:36 UTC by TSergey1

Корректировка isort и flake8

2024-01-05 06:14 UTC, rakikz approved these changes

2024-01-06 14:19 UTC, sukhovarina approved these changes

2024-01-07 19:57 UTC, BnamoRS approved these changes

2024-01-09 09:49 UTC, valerycode requested changes
Отличная работа! Здорово, что учел предыдущие замечания. См. комментарии(больше по оформлению кода).

2024-01-09 09:49 UTC, valerycode commented on .gitignore
> -
А зачем нам папка data в репозитории? Может ты ее случайно из .gitignore удалил?

2024-01-09 09:49 UTC, valerycode commented on parsing_stores/lenta/scr/scr_products.py
>      'store' - словарь данных магазина
Среди аргументов функции нет переменной store, а в Docstring есть. Проверь, пожалуйста.

2024-01-09 09:49 UTC, valerycode commented on parsing_stores/lenta/scr/scr_products.py
>      Получить список продуктов в определеной категории и записать его в файл.
Ты в этой функции не записываешь данные в файл. Надо откорректировать описание в Docstring.

2024-01-09 09:49 UTC, valerycode commented on parsing_stores/lenta/scr/scr_products.py
> +        'pageId': 'cc4fe51d-b4c0-4c96-be9b-ffebb9d67753',
Что за переменная pageId?

2024-01-09 09:49 UTC, valerycode commented on parsing_stores/lenta/scr/scr_products.py
> +                if product_page and product_page != []:
Тут 2 раза проверка на одно и то же получается, так как пустой список возвращает False. Можно данную проверку сократить до: `if product_page:`

2024-01-09 09:49 UTC, valerycode commented on parsing_stores/lenta/scr/scr_products.py
> +        products_data.append(products_in_store)
Nit: создание списка считается затратной операцией(здесь и в других местах кода). Может можно использовать генераторы?(идея для оптимизации) Пример использования генераторов - https://github.com/valerycode/etl_pipeline/blob/main/postgres_to_es/etl/extract_from_postgres.py

2024-01-09 09:49 UTC, valerycode commented on parsing_stores/lenta/scr/scr_products.py
>      return all_products_store, store
Было бы здорово в логи выводить следующую информацию: сколько продуктов по магазину было спарсено, сколько было потом добавлено/обновлено в БД(чтобы было видно, например, что при добавлении/обновлении данных в БД часть данных была потеряна). Например, по магазину А было спарсено 100 товаров и только 20 товаров было добавлено/обновлено в БД(значит была какая-то ошибка при добавлении товаров в БД).

2024-01-09 18:14 UTC, merged

2024-01-09 19:37 UTC, TSergey1 commented on parsing_stores/lenta/scr/scr_products.py
> +        'pageId': 'cc4fe51d-b4c0-4c96-be9b-ffebb9d67753',
благодаря pageId получаем страницу на сайте только со скидочными товарами. Раньше я парсил без этого параметра. Получал все товары в магазине и фильтровал их по наличию скидки.

2024-01-09 19:38 UTC, TSergey1 commented on .gitignore
> -
Эта папка для временных файлов json при парсинге