Новый кверисет для отзывов. Новая ручка для отзывов пользователя
Mobile-app-promotions-and-discounts/backend pull request #92
Opened 2024-01-15 19:03 UTC by sukhovarina

Написала новую ручку для "Моих отзывов" пользователя, теперь он будет видеть весь список своих отзывов.
Написала кверисет для методов post и delete для добавления и удаления отзывов на товары.

2024-01-21 16:03 UTC, valerycode requested changes
См. комментарии

2024-01-21 16:03 UTC, valerycode commented on api/urls.py
> +router.register('users/reviews', UserReviewsViewSet, basename='user-reviews')
Может исправим `users/reviews` на `user-reviews`(такая запись эндпоинта является корректной, проверила:)

2024-01-22 18:56 UTC, BnamoRS reviewed
Не понял некоторые моменты  по работе action. Оставил комментарии. Посмотри пожалуйста.

2024-01-22 18:56 UTC, BnamoRS commented on api/views.py
> +            if Review.objects.filter(user=user, review=queryset).exists():
В модели Review кажется нет поля rewiev. Как будет работать фильтрация?

2024-01-22 18:56 UTC, BnamoRS commented on api/views.py
> +            Review.objects.create(user=user, review=queryset)
Здесь тоже. см. комментарий выше.

2024-01-22 18:56 UTC, BnamoRS commented on api/views.py
> +        queryset = get_object_or_404(Review, pk=pk)
Возможно здесь стоит искать продукт? При создании отзыва на продукт в модели Review мы не найдем этот отзыв. Его еще нет. Или я ошибаюсь?

2024-01-22 18:56 UTC, BnamoRS commented on api/views.py
> +        user_review = Review.objects.filter(user=user, review=queryset)
См. комментарий выше.

2024-01-22 18:56 UTC, BnamoRS commented on api/views.py
> +class UserReviewsViewSet(viewsets.ModelViewSet):
Если здесь мы только получаем отзывы по пользователю, тогда может лучше ReadOnlyModelViewSet ?

2024-01-23 12:04 UTC, valerycode commented on api/views.py
> +        queryset = get_object_or_404(Review, pk=pk)
@BnamoRS верно подметил)

2024-01-23 15:29 UTC, TSergey1 approved these changes

2024-01-31 16:27 UTC, BnamoRS approved these changes

2024-02-02 16:48 UTC, valerycode reviewed
См. замечания

2024-02-02 16:48 UTC, valerycode commented on api/serializers.py
> +        if self.context['request'].method != 'POST':
У тебя получается, что неважно выполняется оператор if или нет, возвращается data. Надо поправить логику.

2024-02-02 16:48 UTC, valerycode commented on api/views.py
>      filter_backends = (OrderingFilter,)
Почему то поля для фильтрации в базовом классе, а сам фильтр в наследнике. Логично все, что относится к фильтру тогда записать в базовом классе.

2024-02-06 16:32 UTC, valerycode requested changes
См.замечания

2024-02-06 16:32 UTC, valerycode commented on api/permissions.py
> +                or request.user.is_admin
У нас у пользователя нет свойства is_admin - если уберешь request.user.is_staff и оставишь только request.user.is_admin, то поймаешь ошибку

2024-02-07 18:26 UTC, merged